### PR TITLE
[bug] The repeat count info is not working.

### PR DESCRIPTION
**Pull request by cabbage98**
**The repeat count info is not working.**

The repleatCount in png metadata means that repeat animation after end of the last play.
So #0 means that 1 time animation from first frame.
#1 means that 2 times repeat.
#2 means that 3 time repeat.

REF. https://wiki.mozilla.org/APNG_Specification
`num_plays` indicates the number of times that this animation should play; if it is 0, the animation should play indefinitely. If nonzero, the animation should come to rest on the final frame at the end of the last play.

### CODE REVIEW

**Comment by onevcat** [comment]
Sorry for the late reply.

The `repeatCount` is set to `num_plays  - 1` when creating the `APNGImage`, so I guess the logic here should be fine, that if `repeatCount == 0`, it means there is no repeat and only playing for once. @cabbage98  How do you think about it?

**Comment by GuanshanLiu** [comment]
@onevcat is there any update on this? 

> num_plays indicates the number of times that this animation should play; if it is 0, the animation should play indefinitely. If nonzero, the animation should come to rest on the final frame at the end of the last play.

I face the same requirement now. 0 for playing indefinitely.

**Comment by axl411** [comment]
FYI in my project, the actual behavior is that the animation playing count matches the repeatCount. So the animation loop count is always 1 time less than expected, and when `repeatCount = 0`, the animation doesn't play.

This is found by my QA and I just added 1 to the repeatCount (expect for the -1 case) to work around this.

How I use APNGKit (code is for demonstration only):
```
let imageView = APNGImageView()
let image = APNGImage(data: data)
if image.repeatCount != APNGKit.RepeatForever {
    image.repeatCount += 1
}
imageView.image = image
imageView.startAnimating()
```

(We're using APNGKit 1.2.0)

**Comment by onevcat** [comment]
The `repeatCount` is confusing by the name and it is now removed in the newly released APNGKit v2. In the latest version, please use `numberOfPlays` to get and set the animation play loop count, which also aligns to the APNG spec.

I am closing this for now.

**Comment by eJamesLin** [comment]
For reference, this issue is fixed at this pull-request https://github.com/onevcat/APNGKit/pull/120

**Pull request closed without merging**
