### PR TITLE
optimize cpu load to build next frame by first progressive decoding

### PR DESCRIPTION
**Pull request by netmaid**
There is problem on APNGImage.next(currentIndex:) that consume cpu load almost 70% of total 24%.

Test environment: iPhone 6s, iOS 10.1.1
Demo app: APNGDemo-iOS
APNG file: spinfox.apng

I've fixed it to build next frame by first progressive decoding.

Let me know if it has any problems.
Thank you.

## Before

cpu
profile

## After

final

### CODE REVIEW

**Comment by onevcat** [comment]
It's a tradeoff between CPU time and memory usage. I believe you could get the same effect (of caching all frames) by setting `progressive` to `false` in the APNG image creating method.

**Comment by netmaid** [comment]
It would be delayed to animate until all frame of animation loaded by setting `progressive` to `false` especially on big size or many frame of APNG.
And I think APNGImageCache will limit the memory flooding if she or he configure `totalCostLimit` or `countLimit`.
Or may I have another options?

**Comment by onevcat** [comment]
Your approach is basically the same as setting `progressive` to `false`, which will also hold all the decoded frame data, so the performance would be almost the same (by using more memory and less CPU).

**Comment by netmaid** [comment]
Yes, I understood your opinion and that's right in terms of approach and agree it.

Let me explain about it more details.

You know CPU too much for decoding whole frames right now when some heavy APNG has many frames about 100 or more and it's size about 5MB or bigger.
So I think it's useful to decode progressively frame by frame and CPU have enough time to decode very large APNG. But memory usage is very heavy the same as setting `progressive` to `false`.

I guess you think this feature is inappropriate to `progressive` and me too.

This PR is just my opinion how to render APNG with less CPU steadily with less memory usage.
Of course, more enhancement needed to consume less memory with keeping cache's limit like dropping old frames which exceeded memory.

Thank you for understanding my misleading and subjective opinions.

**Comment by onevcat** [comment]
@netmaid Great explanation. Thank you!

Yes, it is never easy to make these two (CPU and memory) works perfectly together.

The `progressive` option was mainly developed for reducing memory pressure (at least in my own apps). I am quite sorry for the bad name, but `progressive` truly means "loading frames one by one AND only keep the one which is showing to save memory" instead of "loading frames one by one and keep them all".

It would be good to give this behavior another name (maybe something like `incremental`? I am not English speaker so it's hard for me to pick up the best name..). Do you have any better ideas?

And the `totalCostLimit` or `countLimit` cache is another story. It's related to give a limitation to a few fully decoded APNG images, instead of a single one. Sometimes just one huge APNG image would make you a headache about the memory usage. XD

**Comment by netmaid** [comment]
How about another parameter with name `keepFrames`?
Sorry, I'm also not native speaker of English as you know.

**Pull request closed without merging**
