### PR TITLE
Migration to Swift 4

### PR DESCRIPTION
**Pull request by Sega-Zero**
Few code changes to support swift 4 and XCode 9

### CODE REVIEW

**Comment by onevcat** [comment]
@Sega-Zero Thanks for that. I'd take a look at this and make other necessary changes.

**Comment by Sega-Zero** [comment]
Made a few more changes, forgot to check the tests and macOS target

**Comment by onevcat** [comment]
@Sega-Zero Great work!

Actually I am trying to upgrade it to Swift 4 in this branch too: https://github.com/onevcat/APNGKit/tree/swift4, also with an upgrade of libpng, as well as supporting for Swift 3.2.

Your commits become  great reference to me to migrate to the new version. Thank you!

I will make a few changes as well and release a version later for the new version.

**Comment by Sega-Zero** [comment]
I can change the base branch to swift4, if you want :)

**Comment by onevcat** [comment]
:] I think it would be easier to just use that branch. It should contain all changes here as well as more upgrade in libpng and Swift 3.2 compatibility.

I am release a 1.0.0 version now. Thank you very much for your contribution!

**Pull request closed without merging**
